// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetHelloRequest struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHelloRequest) Reset()         { *m = GetHelloRequest{} }
func (m *GetHelloRequest) String() string { return proto.CompactTextString(m) }
func (*GetHelloRequest) ProtoMessage()    {}
func (*GetHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *GetHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHelloRequest.Unmarshal(m, b)
}
func (m *GetHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHelloRequest.Marshal(b, m, deterministic)
}
func (m *GetHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHelloRequest.Merge(m, src)
}
func (m *GetHelloRequest) XXX_Size() int {
	return xxx_messageInfo_GetHelloRequest.Size(m)
}
func (m *GetHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHelloRequest proto.InternalMessageInfo

func (m *GetHelloRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type GetHelloResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHelloResponse) Reset()         { *m = GetHelloResponse{} }
func (m *GetHelloResponse) String() string { return proto.CompactTextString(m) }
func (*GetHelloResponse) ProtoMessage()    {}
func (*GetHelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *GetHelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHelloResponse.Unmarshal(m, b)
}
func (m *GetHelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHelloResponse.Marshal(b, m, deterministic)
}
func (m *GetHelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHelloResponse.Merge(m, src)
}
func (m *GetHelloResponse) XXX_Size() int {
	return xxx_messageInfo_GetHelloResponse.Size(m)
}
func (m *GetHelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHelloResponse proto.InternalMessageInfo

func (m *GetHelloResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*GetHelloRequest)(nil), "main.GetHelloRequest")
	proto.RegisterType((*GetHelloResponse)(nil), "main.GetHelloResponse")
}

func init() {
	proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce)
}

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xd2, 0xe5,
	0xe2, 0x77, 0x4f, 0x2d, 0xf1, 0x00, 0x89, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49,
	0x71, 0x71, 0xa4, 0x17, 0xa5, 0xa6, 0x96, 0x64, 0xe6, 0xa5, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0xc1, 0xf9, 0x4a, 0x1a, 0x5c, 0x02, 0x08, 0xe5, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42,
	0x22, 0x5c, 0xac, 0x45, 0xa9, 0x05, 0x39, 0x95, 0x50, 0xc5, 0x10, 0x8e, 0x91, 0x27, 0xc2, 0xe0,
	0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x33, 0x2e, 0x56, 0x30, 0x5f, 0x48, 0x54, 0x0f,
	0x64, 0xb7, 0x1e, 0x9a, 0xc5, 0x52, 0x62, 0xe8, 0xc2, 0x10, 0x0b, 0x92, 0xd8, 0xc0, 0x0e, 0x36,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xba, 0xc3, 0x81, 0xb1, 0xbf, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetHelloServiceClient is the client API for GetHelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetHelloServiceClient interface {
	Hello(ctx context.Context, in *GetHelloRequest, opts ...grpc.CallOption) (*GetHelloResponse, error)
}

type getHelloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetHelloServiceClient(cc grpc.ClientConnInterface) GetHelloServiceClient {
	return &getHelloServiceClient{cc}
}

func (c *getHelloServiceClient) Hello(ctx context.Context, in *GetHelloRequest, opts ...grpc.CallOption) (*GetHelloResponse, error) {
	out := new(GetHelloResponse)
	err := c.cc.Invoke(ctx, "/main.GetHelloService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetHelloServiceServer is the server API for GetHelloService service.
type GetHelloServiceServer interface {
	Hello(context.Context, *GetHelloRequest) (*GetHelloResponse, error)
}

// UnimplementedGetHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGetHelloServiceServer struct {
}

func (*UnimplementedGetHelloServiceServer) Hello(ctx context.Context, req *GetHelloRequest) (*GetHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

func RegisterGetHelloServiceServer(s *grpc.Server, srv GetHelloServiceServer) {
	s.RegisterService(&_GetHelloService_serviceDesc, srv)
}

func _GetHelloService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetHelloServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.GetHelloService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetHelloServiceServer).Hello(ctx, req.(*GetHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetHelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.GetHelloService",
	HandlerType: (*GetHelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _GetHelloService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
